In [1]:
import pandas as pd
import numpy as np
import random

from sklearn import linear_model
from sklearn.metrics import mean_squared_error, r2_score

%matplotlib inline

In [2]:
df = pd.read_csv('INPI.csv', sep=';', decimal=',')

In [3]:
df.head()

ANO  MES  DIA  HORA  TempAr
0  2009    1    1     0    26.5
1  2009    1    1   300    26.0
2  2009    1    1   600    25.5
3  2009    1    1   900    24.5
4  2009    1    1  1200    28.0

In [4]:
for i in range(1,4):
    t_menos_1 = 'temp_t_{}'.format(i)
    df[t_menos_1] = df.TempAr.shift(i)
    t_mais_1 = 'temp_tm{}'.format(i)
    df[t_mais_1] = df.TempAr.shift(-i)

In [5]:
df

ANO  MES  DIA  HORA  TempAr  temp_t_1  temp_tm1  temp_t_2  temp_tm2  \
0     2009    1    1     0    26.5       NaN      26.0       NaN      25.5   
1     2009    1    1   300    26.0      26.5      25.5       NaN      24.5   
2     2009    1    1   600    25.5      26.0      24.5      26.5      28.0   
3     2009    1    1   900    24.5      25.5      28.0      26.0      30.0   
4     2009    1    1  1200    28.0      24.5      30.0      25.5      33.5   
5     2009    1    1  1500    30.0      28.0      33.5      24.5      35.0   
6     2009    1    1  1800    33.5      30.0      35.0      28.0      26.5   
7     2009    1    1  2100    35.0      33.5      26.5      30.0      27.0   
8     2009    1    2     0    26.5      35.0      27.0      33.5      25.5   
9     2009    1    2   300    27.0      26.5      25.5      35.0      25.0   
10    2009    1    2   600    25.5      27.0      25.0      26.5      29.5   
11    2009    1    2   900    25.0      25.5      29.5      27.0      33.5   
12    2009    1    2  1200    29.5      25.0      33.5      25.5      35.0   
13    2009    1    2  1500    33.5      29.5      35.0      25.0      31.5   
14    2009    1    2  1800    35.0      33.5      31.5      29.5      26.0   
15    2009    1    2  2100    31.5      35.0      26.0      33.5      30.5   
16    2009    1    3     0    26.0      31.5      30.5      35.0      27.5   
17    2009    1    3  1500    30.5      26.0      27.5      31.5      22.5   
18    2009    1    3  1800    27.5      30.5      22.5      26.0      25.0   
19    2009    1    3  2100    22.5      27.5      25.0      30.5      25.5   
20    2009    1    3   900    25.0      22.5      25.5      27.5      26.5   
21    2009    1    3   600    25.5      25.0      26.5      22.5      28.0   
22    2009    1    3   300    26.5      25.5      28.0      25.0      27.5   
23    2009    1    3  1200    28.0      26.5      27.5      25.5      27.0   
24    2009    1    4  2100    27.5      28.0      27.0      26.5      24.5   
25    2009    1    4  1800    27.0      27.5      24.5      28.0      22.0   
26    2009    1    4  1500    24.5      27.0      22.0      27.5      21.5   
27    2009    1    4     0    22.0      24.5      21.5      27.0      22.0   
28    2009    1    4   900    21.5      22.0      22.0      24.5      23.0   
29    2009    1    4   600    22.0      21.5      23.0      22.0      23.5   
...    ...  ...  ...   ...     ...       ...       ...       ...       ...   
2714  2009   12  324  1500    29.0      32.5      24.5      34.5      22.5   
2715  2009   12  325     0    24.5      29.0      22.5      32.5      22.5   
2716  2009   12  325   900    22.5      24.5      22.5      29.0      22.5   
2717  2009   12  325   600    22.5      22.5      22.5      24.5      22.5   
2718  2009   12  325   300    22.5      22.5      22.5      22.5      32.0   
2719  2009   12  325  1200    22.5      22.5      32.0      22.5      24.5   
2720  2009   12  325  2100    32.0      22.5      24.5      22.5      31.5   
2721  2009   12  325  1800    24.5      32.0      31.5      22.5      31.5   
2722  2009   12  325  1500    31.5      24.5      31.5      32.0      24.0   
2723  2009   12  326     0    31.5      31.5      24.0      24.5      24.5   
2724  2009   12  326   900    24.0      31.5      24.5      31.5      25.0   
2725  2009   12  326   600    24.5      24.0      25.0      31.5      28.5   
2726  2009   12  326   300    25.0      24.5      28.5      24.0      28.0   
2727  2009   12  326  1200    28.5      25.0      28.0      24.5      28.0   
2728  2009   12  326  2100    28.0      28.5      28.0      25.0      30.0   
2729  2009   12  326  1800    28.0      28.0      30.0      28.5      25.5   
2730  2009   12  326  1500    30.0      28.0      25.5      28.0      22.5   
2731  2009   12  326     0    25.5      30.0      22.5      28.0      22.5   
2732  2009   12  327   900    22.5      25.5      22.5      30.0      22.5   
2733  2009   12  327   600   

In [6]:
for i in range(3,22,3):
    desc_h = 'h{}'.format(i*100)
    df[desc_h] = df.HORA.apply(lambda x: 1 if x == i*100 else 0)

In [7]:
for i in range(1,12):
    desc_m = 'm{}'.format(i)
    df[desc_m] = df.HORA.apply(lambda x: 1 if x == i else 0)

In [8]:
df.head()

ANO  MES  DIA  HORA  TempAr  temp_t_1  temp_tm1  temp_t_2  temp_tm2  \
0  2009    1    1     0    26.5       NaN      26.0       NaN      25.5   
1  2009    1    1   300    26.0      26.5      25.5       NaN      24.5   
2  2009    1    1   600    25.5      26.0      24.5      26.5      28.0   
3  2009    1    1   900    24.5      25.5      28.0      26.0      30.0   
4  2009    1    1  1200    28.0      24.5      30.0      25.5      33.5   

   temp_t_3 ...   m2  m3  m4  m5  m6  m7  m8  m9  m10  m11  
0       NaN ...    0   0   0   0   0   0   0   0    0    0  
1       NaN ...    0   0   0   0   0   0   0   0    0    0  
2       NaN ...    0   0   0   0   0   0   0   0    0    0  
3      26.5 ...    0   0   0   0   0   0   0   0    0    0  
4      26.0 ...    0   0   0   0   0   0   0   0    0    0  

[5 rows x 29 columns]

In [9]:
df = df.dropna()

In [10]:
model = linear_model.LinearRegression()

In [11]:
y = df.TempAr.values.reshape(-1,1)

In [12]:
df.columns[5:]

Index(['temp_t_1', 'temp_tm1', 'temp_t_2', 'temp_tm2', 'temp_t_3', 'temp_tm3',
       'h300', 'h600', 'h900', 'h1200', 'h1500', 'h1800', 'h2100', 'm1', 'm2',
       'm3', 'm4', 'm5', 'm6', 'm7', 'm8', 'm9', 'm10', 'm11'],
      dtype='object')

In [13]:
x = df[df.columns[5:]].values

In [14]:
model.fit(x,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [15]:
model.coef_

array([[  4.33494571e-01,   4.34678999e-01,   2.00673282e-02,
         -2.76753563e-03,   3.93089133e-03,   2.87023790e-03,
          2.62326026e+00,   2.36233094e+00,   1.64105331e+00,
          1.39220763e+00,   4.70234120e+00,   5.10478198e+00,
          5.58755115e+00,   0.00000000e+00,   0.00000000e+00,
          0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          0.00000000e+00,   0.00000000e+00,   0.00000000e+00]])

In [16]:
model.intercept_

array([-0.11640032])

In [17]:
y_pred = model.predict(x)

In [18]:
r2_score(y, y_pred)

0.79083331827171133

In [19]:
from sklearn import svm

In [20]:
model_B  = svm.SVR()

In [21]:
model_B.fit(x,y)

C:\Users\guilh\Anaconda3\lib\site-packages\sklearn\utils\validation.py:526: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVR(C=1.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma='auto',
  kernel='rbf', max_iter=-1, shrinking=True, tol=0.001, verbose=False)

In [22]:
y_pred_b = model_B.predict(x)

In [23]:
r2_score(y, y_pred_b)

0.74851812809503526

In [24]:
model_c = linear_model.LinearRegression()

In [25]:
df['e'] = y - model.predict(x)

C:\Users\guilh\Anaconda3\lib\site-packages\ipykernel\__main__.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':


In [26]:
for i in range(1,3):
    e_menos_1 = 'e_{}'.format(i)
    df[e_menos_1] = df.e.shift(i)
    e_mais_1 = 'em{}'.format(i)
    df[e_mais_1] = df.e.shift(-i)
df.head()

C:\Users\guilh\Anaconda3\lib\site-packages\ipykernel\__main__.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  app.launch_new_instance()
C:\Users\guilh\Anaconda3\lib\site-packages\ipykernel\__main__.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy


ANO  MES  DIA  HORA  TempAr  temp_t_1  temp_tm1  temp_t_2  temp_tm2  \
3  2009    1    1   900    24.5      25.5      28.0      26.0      30.0   
4  2009    1    1  1200    28.0      24.5      30.0      25.5      33.5   
5  2009    1    1  1500    30.0      28.0      33.5      24.5      35.0   
6  2009    1    1  1800    33.5      30.0      35.0      28.0      26.5   
7  2009    1    1  2100    35.0      33.5      26.5      30.0      27.0   

   temp_t_3    ...     m7  m8  m9  m10  m11         e       e_1       em1  \
3      26.5    ...      0   0   0    0    0 -0.888823       NaN  2.441540   
4      26.0    ...      0   0   0    0    0  2.441540 -0.888823 -1.856620   
5      25.5    ...      0   0   0    0    0 -1.856620  2.441540 -0.369333   
6      24.5    ...      0   0   0    0    0 -0.369333 -1.856620  2.777235   
7      28.0    ...      0   0   0    0    0  2.777235 -0.369333 -1.083609   

        e_2       em2  
3       NaN -1.856620  
4       NaN -0.369333  
5 -0.888823  2.777235  
6  2.441540 -1.083609  
7 -1.856620  1.071694  

[5 rows x 34 columns]

In [27]:
df = df.dropna()

In [28]:
df.drop(columns='e', inplace=True)

In [29]:
x1 = df[df.columns[5:]].values
y = df.TempAr.values.reshape(-1,1)

In [30]:
model_c.fit(x1, y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [31]:
model_c.coef_

array([[  1.12284027e+00,   1.09617088e+00,  -4.86254311e-01,
         -5.50289028e-01,  -2.01501843e-02,   5.09479358e-02,
          3.27789172e+00,   2.46512370e+00,   4.49206549e+00,
         -1.21025954e+00,   1.58731430e+00,  -3.72849580e+00,
          8.42165825e-01,   0.00000000e+00,   3.33066907e-16,
          1.33226763e-15,   0.00000000e+00,   0.00000000e+00,
          0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
         -1.13847382e+00,  -1.06422475e+00,  -1.83784475e-02,
          8.13574037e-02]])

In [32]:
model_c.intercept_

array([-6.54825101])

In [33]:
r2_score(y, model_c.predict(x1))

0.98023667198560005